stages:
  - test
  - build
  - deploy

test_stage:
  stage: test
  image: ubuntu:22.04
  script:
    - apt update 
    - apt install -y pylint
    - pylint cam_handler.py
  allow_failure: true
  
build_stage:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - ls /kaniko
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/dockerfile" --destination ${CI_REGISTRY_IMAGE}:$CI_COMMIT_TAG  --destination ${CI_REGISTRY_IMAGE}:latest
  rules:
    - if: $CI_COMMIT_TAG


deploy_stage:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context video/cam_handler:office
    -   kubectl set image deployment.apps/cam-handler-deployment *=${CI_REGISTRY_IMAGE}:latest -n videoserver
  allow_failure: true
   rules:
    - if: $CI_COMMIT_TAG

