stages:
  - build

build_stage:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/dockerfile"
      --destination "${CI_REGISTRY_IMAGE}"
  #rules:
  #  - if: $CI_COMMIT_TAG